package main

import (
	"bytes"
	"context"
	"crypto/tls"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"runtime"
	"strconv"
	"strings"
	"time"
)

// The League Client API is local and unsupported by Riot. Its lockfile is
// generated by the running client; never store or print its password.
type leagueClient struct {
	base, password string
	http           *http.Client
}

func leagueLockfilePath() (string, error) {
	override := strings.TrimSpace(os.Getenv("MATCHUP_LCU_LOCKFILE"))
	if override != "" {
		return override, nil
	}
	var fallback string
	switch runtime.GOOS {
	case "windows":
		fallback = `C:\Riot Games\League of Legends\lockfile`
	case "darwin":
		fallback = "/Applications/League of Legends.app/Contents/LoL/lockfile"
	default:
		return "", fmt.Errorf("set MATCHUP_LCU_LOCKFILE to the running League Client lockfile")
	}
	executables, _ := runningLeagueClientPaths()
	return resolveLeagueLockfile("", executables, fallback)
}

func resolveLeagueLockfile(override string, executables []string, fallback string) (string, error) {
	if override != "" {
		return override, nil
	}
	for _, executable := range executables {
		path := filepath.Join(filepath.Dir(executable), "lockfile")
		if info, err := os.Stat(path); err == nil && !info.IsDir() {
			return path, nil
		}
	}
	if info, err := os.Stat(fallback); err == nil && !info.IsDir() {
		return fallback, nil
	}
	return "", fmt.Errorf("LeagueClient.exe lockfile not found (checked running client and %s); open the League of Legends client, or set MATCHUP_LCU_LOCKFILE", fallback)
}

func connectLeagueClient() (*leagueClient, error) {
	path, err := leagueLockfilePath()
	if err != nil {
		return nil, err
	}
	content, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("League Client is not running or lockfile is elsewhere; set MATCHUP_LCU_LOCKFILE: %w", err)
	}
	parts := strings.Split(strings.TrimSpace(string(content)), ":")
	if len(parts) != 5 || parts[0] != "LeagueClient" || parts[4] != "https" {
		return nil, fmt.Errorf("invalid League Client lockfile")
	}
	port, err := strconv.Atoi(parts[2])
	if err != nil || port < 1 || port > 65535 || parts[3] == "" {
		return nil, fmt.Errorf("invalid League Client lockfile")
	}
	// Riot's local client serves a self-signed certificate. TLS relaxation is
	// limited to this HTTP client, which only contacts 127.0.0.1.
	transport := &http.Transport{TLSClientConfig: &tls.Config{InsecureSkipVerify: true}} //nolint:gosec
	return &leagueClient{base: fmt.Sprintf("https://127.0.0.1:%d", port), password: parts[3],
		http: &http.Client{Timeout: 20 * time.Second, Transport: transport, CheckRedirect: func(*http.Request, []*http.Request) error { return http.ErrUseLastResponse }}}, nil
}

func (c *leagueClient) request(ctx context.Context, method, path string, dst any) error {
	var body io.Reader
	if method == http.MethodPost {
		body = bytes.NewBufferString(`{"componentType":"matchHistory"}`)
	}
	req, err := http.NewRequestWithContext(ctx, method, c.base+path, body)
	if err != nil {
		return err
	}
	req.SetBasicAuth("riot", c.password)
	if body != nil {
		req.Header.Set("Content-Type", "application/json")
	}
	resp, err := c.http.Do(req)
	if err != nil {
		return fmt.Errorf("League Client request failed: %w", err)
	}
	defer resp.Body.Close()
	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		message, _ := io.ReadAll(io.LimitReader(resp.Body, 300))
		return fmt.Errorf("League Client HTTP %d: %s", resp.StatusCode, strings.TrimSpace(string(message)))
	}
	if dst != nil {
		return json.NewDecoder(io.LimitReader(resp.Body, 1<<20)).Decode(dst)
	}
	return nil
}

func replayMatchID(matchID string) (string, string, error) {
	parts := strings.Split(matchID, "_")
	if len(parts) != 2 || parts[0] == "" || parts[1] == "" {
		return "", "", fmt.Errorf("invalid match ID %q", matchID)
	}
	if _, err := strconv.ParseUint(parts[1], 10, 64); err != nil {
		return "", "", fmt.Errorf("invalid match ID %q", matchID)
	}
	return strings.ToUpper(parts[0]), parts[1], nil
}

func openReplay(ctx context.Context, c *leagueClient, matchID string) error {
	platform, gameID, err := replayMatchID(matchID)
	if err != nil {
		return err
	}
	var locale struct {
		Region string `json:"region"`
	}
	if err := c.request(ctx, http.MethodGet, "/riotclient/region-locale", &locale); err != nil {
		return err
	}
	if !strings.EqualFold(locale.Region, platformLabel(platform)) {
		return fmt.Errorf("match is on %s; League Client is on %s", platformLabel(platform), locale.Region)
	}
	var folder string
	if err := c.request(ctx, http.MethodGet, "/lol-replays/v1/rofls/path", &folder); err != nil {
		return err
	}
	if folder == "" {
		return fmt.Errorf("League Client returned no replay folder")
	}
	file := filepath.Join(folder, platform+"-"+gameID+".rofl")
	info, statErr := os.Stat(file)
	if os.IsNotExist(statErr) || (statErr == nil && info.Size() <= 1024) {
		path := "/lol-replays/v1/rofls/" + gameID + "/download/graceful"
		if err := c.request(ctx, http.MethodPost, path, nil); err != nil {
			return fmt.Errorf("replay download failed: %w", err)
		}
		deadline := time.NewTimer(45 * time.Second)
		defer deadline.Stop()
		tick := time.NewTicker(500 * time.Millisecond)
		defer tick.Stop()
		var previousSize int64
		stable := 0
		for {
			if current, err := os.Stat(file); err == nil && current.Size() > 1024 {
				if current.Size() == previousSize {
					stable++
				} else {
					stable = 0
				}
				previousSize = current.Size()
				if stable >= 2 {
					break
				}
			}
			select {
			case <-ctx.Done():
				return ctx.Err()
			case <-deadline.C:
				return fmt.Errorf("League Client did not finish downloading %s; check its match history", matchID)
			case <-tick.C:
			}
		}
	} else if statErr != nil {
		return statErr
	}
	if err := c.request(ctx, http.MethodPost, "/lol-replays/v1/rofls/"+gameID+"/watch", nil); err != nil {
		return fmt.Errorf("replay could not start (check the current patch): %w", err)
	}
	return nil
}
