// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: champions.sql

package store

import (
	"context"
)

const listChampions = `-- name: ListChampions :many
SELECT id, display_name FROM champions
UNION
SELECT DISTINCT champion, champion FROM match_participants
WHERE champion <> '' AND champion NOT IN (SELECT id FROM champions)
ORDER BY 2 COLLATE NOCASE
`

// Catalog champions plus any champion seen in stored matches but missing
// from the catalog (e.g. a release newer than the cached Data Dragon copy).
func (q *Queries) ListChampions(ctx context.Context) ([]Champion, error) {
	rows, err := q.db.QueryContext(ctx, listChampions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Champion{}
	for rows.Next() {
		var i Champion
		if err := rows.Scan(&i.ID, &i.DisplayName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertChampion = `-- name: UpsertChampion :exec
INSERT INTO champions (id, display_name) VALUES (?, ?)
ON CONFLICT (id) DO UPDATE SET display_name = excluded.display_name
`

type UpsertChampionParams struct {
	ID          string
	DisplayName string
}

func (q *Queries) UpsertChampion(ctx context.Context, arg UpsertChampionParams) error {
	_, err := q.db.ExecContext(ctx, upsertChampion, arg.ID, arg.DisplayName)
	return err
}
