// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: keys.sql

package store

import (
	"context"
)

const addRiotKey = `-- name: AddRiotKey :exec
INSERT INTO riot_keys (label, value, added_at) VALUES (?, ?, ?)
ON CONFLICT (value) DO UPDATE SET label = excluded.label, rejected_at = 0, rejection = ''
`

type AddRiotKeyParams struct {
	Label   string
	Value   string
	AddedAt int64
}

// Re-adding a known key renames it and clears its rejection.
func (q *Queries) AddRiotKey(ctx context.Context, arg AddRiotKeyParams) error {
	_, err := q.db.ExecContext(ctx, addRiotKey, arg.Label, arg.Value, arg.AddedAt)
	return err
}

const deleteRiotKey = `-- name: DeleteRiotKey :exec
DELETE FROM riot_keys WHERE id = ?
`

func (q *Queries) DeleteRiotKey(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteRiotKey, id)
	return err
}

const listRiotKeys = `-- name: ListRiotKeys :many
SELECT id, label, value, added_at, rejected_at, rejection FROM riot_keys ORDER BY id
`

func (q *Queries) ListRiotKeys(ctx context.Context) ([]RiotKey, error) {
	rows, err := q.db.QueryContext(ctx, listRiotKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RiotKey{}
	for rows.Next() {
		var i RiotKey
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.Value,
			&i.AddedAt,
			&i.RejectedAt,
			&i.Rejection,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectRiotKey = `-- name: RejectRiotKey :exec
UPDATE riot_keys SET rejected_at = ?, rejection = ? WHERE id = ?
`

type RejectRiotKeyParams struct {
	RejectedAt int64
	Rejection  string
	ID         int64
}

func (q *Queries) RejectRiotKey(ctx context.Context, arg RejectRiotKeyParams) error {
	_, err := q.db.ExecContext(ctx, rejectRiotKey, arg.RejectedAt, arg.Rejection, arg.ID)
	return err
}
