// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: matches.sql

package store

import (
	"context"
	"database/sql"
)

const countTrackedGames = `-- name: CountTrackedGames :one
SELECT COUNT(*) FROM tracked_games
`

func (q *Queries) CountTrackedGames(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTrackedGames)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteMatchesBeforePatch = `-- name: DeleteMatchesBeforePatch :execrows
DELETE FROM matches
WHERE patch_major < ?1 OR (patch_major = ?1 AND patch_minor < ?2)
`

type DeleteMatchesBeforePatchParams struct {
	Major int64
	Minor int64
}

func (q *Queries) DeleteMatchesBeforePatch(ctx context.Context, arg DeleteMatchesBeforePatchParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteMatchesBeforePatch, arg.Major, arg.Minor)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteParticipantsBeforePatch = `-- name: DeleteParticipantsBeforePatch :exec
DELETE FROM match_participants WHERE match_id IN (
    SELECT match_id FROM matches
    WHERE patch_major < ?1 OR (patch_major = ?1 AND patch_minor < ?2))
`

type DeleteParticipantsBeforePatchParams struct {
	Major int64
	Minor int64
}

func (q *Queries) DeleteParticipantsBeforePatch(ctx context.Context, arg DeleteParticipantsBeforePatchParams) error {
	_, err := q.db.ExecContext(ctx, deleteParticipantsBeforePatch, arg.Major, arg.Minor)
	return err
}

const deleteTrackedGamesBeforePatch = `-- name: DeleteTrackedGamesBeforePatch :exec

DELETE FROM tracked_games WHERE match_id IN (
    SELECT match_id FROM matches
    WHERE patch_major < ?1 OR (patch_major = ?1 AND patch_minor < ?2))
`

type DeleteTrackedGamesBeforePatchParams struct {
	Major int64
	Minor int64
}

// Replays expire with each patch, so older matches are pruned. match_checks
// keeps their IDs so the next update does not download them again.
func (q *Queries) DeleteTrackedGamesBeforePatch(ctx context.Context, arg DeleteTrackedGamesBeforePatchParams) error {
	_, err := q.db.ExecContext(ctx, deleteTrackedGamesBeforePatch, arg.Major, arg.Minor)
	return err
}

const getMatchRaw = `-- name: GetMatchRaw :one
SELECT raw_gz FROM matches WHERE match_id = ?
`

func (q *Queries) GetMatchRaw(ctx context.Context, matchID string) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, getMatchRaw, matchID)
	var raw_gz []byte
	err := row.Scan(&raw_gz)
	return raw_gz, err
}

const insertParticipant = `-- name: InsertParticipant :exec
INSERT OR IGNORE INTO match_participants
    (match_id, puuid, riot_id_game_name, riot_id_tagline, champion, team_id,
     team_position, individual_position, lane, win, kills, deaths, assists, cs, gold,
     item0, item1, item2, item3, item4, item5, item6,
     summoner1_id, summoner2_id, keystone, secondary_rune1, secondary_rune2)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertParticipantParams struct {
	MatchID            string
	Puuid              string
	RiotIDGameName     string
	RiotIDTagline      string
	Champion           string
	TeamID             int64
	TeamPosition       string
	IndividualPosition string
	Lane               string
	Win                bool
	Kills              int64
	Deaths             int64
	Assists            int64
	Cs                 int64
	Gold               int64
	Item0              int64
	Item1              int64
	Item2              int64
	Item3              int64
	Item4              int64
	Item5              int64
	Item6              int64
	Summoner1ID        sql.NullInt64
	Summoner2ID        sql.NullInt64
	Keystone           sql.NullInt64
	SecondaryRune1     sql.NullInt64
	SecondaryRune2     sql.NullInt64
}

func (q *Queries) InsertParticipant(ctx context.Context, arg InsertParticipantParams) error {
	_, err := q.db.ExecContext(ctx, insertParticipant,
		arg.MatchID,
		arg.Puuid,
		arg.RiotIDGameName,
		arg.RiotIDTagline,
		arg.Champion,
		arg.TeamID,
		arg.TeamPosition,
		arg.IndividualPosition,
		arg.Lane,
		arg.Win,
		arg.Kills,
		arg.Deaths,
		arg.Assists,
		arg.Cs,
		arg.Gold,
		arg.Item0,
		arg.Item1,
		arg.Item2,
		arg.Item3,
		arg.Item4,
		arg.Item5,
		arg.Item6,
		arg.Summoner1ID,
		arg.Summoner2ID,
		arg.Keystone,
		arg.SecondaryRune1,
		arg.SecondaryRune2,
	)
	return err
}

const insertTrackedGame = `-- name: InsertTrackedGame :exec
INSERT OR IGNORE INTO tracked_games
    (match_id, player_puuid, opponent_puuid, player_rank_tier, player_rank_division,
     player_position, opponent_position, matchup_status)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertTrackedGameParams struct {
	MatchID            string
	PlayerPuuid        string
	OpponentPuuid      string
	PlayerRankTier     string
	PlayerRankDivision string
	PlayerPosition     string
	OpponentPosition   string
	MatchupStatus      string
}

func (q *Queries) InsertTrackedGame(ctx context.Context, arg InsertTrackedGameParams) error {
	_, err := q.db.ExecContext(ctx, insertTrackedGame,
		arg.MatchID,
		arg.PlayerPuuid,
		arg.OpponentPuuid,
		arg.PlayerRankTier,
		arg.PlayerRankDivision,
		arg.PlayerPosition,
		arg.OpponentPosition,
		arg.MatchupStatus,
	)
	return err
}

const isChecked = `-- name: IsChecked :one
SELECT EXISTS (SELECT 1 FROM match_checks WHERE match_id = ? AND player_puuid = ?)
`

type IsCheckedParams struct {
	MatchID     string
	PlayerPuuid string
}

func (q *Queries) IsChecked(ctx context.Context, arg IsCheckedParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isChecked, arg.MatchID, arg.PlayerPuuid)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const latestPatch = `-- name: LatestPatch :one
SELECT patch_major, patch_minor FROM matches
ORDER BY patch_major DESC, patch_minor DESC LIMIT 1
`

type LatestPatchRow struct {
	PatchMajor int64
	PatchMinor int64
}

func (q *Queries) LatestPatch(ctx context.Context) (LatestPatchRow, error) {
	row := q.db.QueryRowContext(ctx, latestPatch)
	var i LatestPatchRow
	err := row.Scan(&i.PatchMajor, &i.PatchMinor)
	return i, err
}

const listMatchesMissingLoadout = `-- name: ListMatchesMissingLoadout :many
SELECT m.match_id, m.platform FROM matches m
WHERE EXISTS (SELECT 1 FROM tracked_games g WHERE g.match_id = m.match_id)
  AND EXISTS (
      SELECT 1 FROM match_participants p
      WHERE p.match_id = m.match_id AND (p.summoner1_id IS NULL OR p.keystone IS NULL))
ORDER BY m.game_creation DESC
`

type ListMatchesMissingLoadoutRow struct {
	MatchID  string
	Platform string
}

func (q *Queries) ListMatchesMissingLoadout(ctx context.Context) ([]ListMatchesMissingLoadoutRow, error) {
	rows, err := q.db.QueryContext(ctx, listMatchesMissingLoadout)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMatchesMissingLoadoutRow{}
	for rows.Next() {
		var i ListMatchesMissingLoadoutRow
		if err := rows.Scan(&i.MatchID, &i.Platform); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markChecked = `-- name: MarkChecked :exec
INSERT OR IGNORE INTO match_checks (match_id, player_puuid) VALUES (?, ?)
`

type MarkCheckedParams struct {
	MatchID     string
	PlayerPuuid string
}

func (q *Queries) MarkChecked(ctx context.Context, arg MarkCheckedParams) error {
	_, err := q.db.ExecContext(ctx, markChecked, arg.MatchID, arg.PlayerPuuid)
	return err
}

const matchNeedsLoadout = `-- name: MatchNeedsLoadout :one
SELECT EXISTS (
    SELECT 1 FROM match_participants
    WHERE match_id = ? AND (summoner1_id IS NULL OR keystone IS NULL)
)
`

func (q *Queries) MatchNeedsLoadout(ctx context.Context, matchID string) (bool, error) {
	row := q.db.QueryRowContext(ctx, matchNeedsLoadout, matchID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateParticipantLoadout = `-- name: UpdateParticipantLoadout :exec
UPDATE match_participants
SET summoner1_id = ?, summoner2_id = ?, keystone = ?, secondary_rune1 = ?, secondary_rune2 = ?
WHERE match_id = ? AND puuid = ?
`

type UpdateParticipantLoadoutParams struct {
	Summoner1ID    sql.NullInt64
	Summoner2ID    sql.NullInt64
	Keystone       sql.NullInt64
	SecondaryRune1 sql.NullInt64
	SecondaryRune2 sql.NullInt64
	MatchID        string
	Puuid          string
}

func (q *Queries) UpdateParticipantLoadout(ctx context.Context, arg UpdateParticipantLoadoutParams) error {
	_, err := q.db.ExecContext(ctx, updateParticipantLoadout,
		arg.Summoner1ID,
		arg.Summoner2ID,
		arg.Keystone,
		arg.SecondaryRune1,
		arg.SecondaryRune2,
		arg.MatchID,
		arg.Puuid,
	)
	return err
}

const upsertMatch = `-- name: UpsertMatch :exec
INSERT INTO matches
    (match_id, platform, game_version, patch_major, patch_minor,
     game_creation, game_duration, queue_id, fetched_at, raw_gz)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (match_id) DO UPDATE SET
    raw_gz = excluded.raw_gz,
    fetched_at = excluded.fetched_at
`

type UpsertMatchParams struct {
	MatchID      string
	Platform     string
	GameVersion  string
	PatchMajor   int64
	PatchMinor   int64
	GameCreation int64
	GameDuration int64
	QueueID      int64
	FetchedAt    int64
	RawGz        []byte
}

func (q *Queries) UpsertMatch(ctx context.Context, arg UpsertMatchParams) error {
	_, err := q.db.ExecContext(ctx, upsertMatch,
		arg.MatchID,
		arg.Platform,
		arg.GameVersion,
		arg.PatchMajor,
		arg.PatchMinor,
		arg.GameCreation,
		arg.GameDuration,
		arg.QueueID,
		arg.FetchedAt,
		arg.RawGz,
	)
	return err
}
