// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"database/sql"
)

type AppSetting struct {
	Key   string
	Value string
}

type Champion struct {
	ID          string
	DisplayName string
}

type Match struct {
	MatchID      string
	Platform     string
	GameVersion  string
	GameCreation int64
	GameDuration int64
	QueueID      int64
	FetchedAt    int64
	PatchMajor   int64
	PatchMinor   int64
	RawGz        []byte
}

type MatchCheck struct {
	MatchID     string
	PlayerPuuid string
}

type MatchParticipant struct {
	MatchID            string
	Puuid              string
	RiotIDGameName     string
	RiotIDTagline      string
	Champion           string
	TeamID             int64
	TeamPosition       string
	IndividualPosition string
	Lane               string
	Win                bool
	Kills              int64
	Deaths             int64
	Assists            int64
	Cs                 int64
	Gold               int64
	Item0              int64
	Item1              int64
	Item2              int64
	Item3              int64
	Item4              int64
	Item5              int64
	Item6              int64
	Summoner1ID        sql.NullInt64
	Summoner2ID        sql.NullInt64
	Keystone           sql.NullInt64
	SecondaryRune1     sql.NullInt64
	SecondaryRune2     sql.NullInt64
}

type Player struct {
	Puuid         string
	GameName      string
	TagLine       string
	Region        string
	Source        string
	RankTier      string
	RankDivision  string
	LeaguePoints  int64
	LastCheckedAt int64
}

type PlayerChampion struct {
	PlayerPuuid string
	Champion    string
}

type PlayerSeed struct {
	GameName      string
	TagLine       string
	Region        string
	Champion      string
	Source        string
	ResolvedPuuid string
}

type TrackedGame struct {
	MatchID            string
	PlayerPuuid        string
	OpponentPuuid      string
	PlayerRankTier     string
	PlayerRankDivision string
	PlayerPosition     string
	OpponentPosition   string
	MatchupStatus      string
}
