// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: players.sql

package store

import (
	"context"
)

const addPlayerChampion = `-- name: AddPlayerChampion :exec
INSERT OR IGNORE INTO player_champions (player_puuid, champion) VALUES (?, ?)
`

type AddPlayerChampionParams struct {
	PlayerPuuid string
	Champion    string
}

func (q *Queries) AddPlayerChampion(ctx context.Context, arg AddPlayerChampionParams) error {
	_, err := q.db.ExecContext(ctx, addPlayerChampion, arg.PlayerPuuid, arg.Champion)
	return err
}

const countPlayers = `-- name: CountPlayers :one
SELECT COUNT(*) FROM players
`

func (q *Queries) CountPlayers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPlayers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deletePlayer = `-- name: DeletePlayer :exec
DELETE FROM players WHERE puuid = ?
`

func (q *Queries) DeletePlayer(ctx context.Context, puuid string) error {
	_, err := q.db.ExecContext(ctx, deletePlayer, puuid)
	return err
}

const deletePlayerChampions = `-- name: DeletePlayerChampions :exec
DELETE FROM player_champions WHERE player_puuid = ?
`

func (q *Queries) DeletePlayerChampions(ctx context.Context, playerPuuid string) error {
	_, err := q.db.ExecContext(ctx, deletePlayerChampions, playerPuuid)
	return err
}

const deletePlayerChecks = `-- name: DeletePlayerChecks :exec
DELETE FROM match_checks WHERE player_puuid = ?
`

func (q *Queries) DeletePlayerChecks(ctx context.Context, playerPuuid string) error {
	_, err := q.db.ExecContext(ctx, deletePlayerChecks, playerPuuid)
	return err
}

const deletePlayerControl = `-- name: DeletePlayerControl :exec
DELETE FROM player_controls WHERE region = ? AND game_name = ? COLLATE NOCASE AND tag_line = ? COLLATE NOCASE
`

type DeletePlayerControlParams struct {
	Region   string
	GameName string
	TagLine  string
}

func (q *Queries) DeletePlayerControl(ctx context.Context, arg DeletePlayerControlParams) error {
	_, err := q.db.ExecContext(ctx, deletePlayerControl, arg.Region, arg.GameName, arg.TagLine)
	return err
}

const deletePlayerGames = `-- name: DeletePlayerGames :exec
DELETE FROM tracked_games WHERE player_puuid = ?
`

func (q *Queries) DeletePlayerGames(ctx context.Context, playerPuuid string) error {
	_, err := q.db.ExecContext(ctx, deletePlayerGames, playerPuuid)
	return err
}

const deleteSeedIdentity = `-- name: DeleteSeedIdentity :exec
DELETE FROM player_seeds WHERE region = ? AND game_name = ? COLLATE NOCASE AND tag_line = ? COLLATE NOCASE
`

type DeleteSeedIdentityParams struct {
	Region   string
	GameName string
	TagLine  string
}

func (q *Queries) DeleteSeedIdentity(ctx context.Context, arg DeleteSeedIdentityParams) error {
	_, err := q.db.ExecContext(ctx, deleteSeedIdentity, arg.Region, arg.GameName, arg.TagLine)
	return err
}

const findPlayerByRiotID = `-- name: FindPlayerByRiotID :one
SELECT puuid, game_name, tag_line, region, rank_tier, rank_division, league_points
FROM players
WHERE game_name = ?1 COLLATE NOCASE AND tag_line = ?2 COLLATE NOCASE AND region = ?3
`

type FindPlayerByRiotIDParams struct {
	GameName string
	TagLine  string
	Region   string
}

type FindPlayerByRiotIDRow struct {
	Puuid        string
	GameName     string
	TagLine      string
	Region       string
	RankTier     string
	RankDivision string
	LeaguePoints int64
}

func (q *Queries) FindPlayerByRiotID(ctx context.Context, arg FindPlayerByRiotIDParams) (FindPlayerByRiotIDRow, error) {
	row := q.db.QueryRowContext(ctx, findPlayerByRiotID, arg.GameName, arg.TagLine, arg.Region)
	var i FindPlayerByRiotIDRow
	err := row.Scan(
		&i.Puuid,
		&i.GameName,
		&i.TagLine,
		&i.Region,
		&i.RankTier,
		&i.RankDivision,
		&i.LeaguePoints,
	)
	return i, err
}

const getPlayer = `-- name: GetPlayer :one
SELECT puuid, game_name, tag_line, region, rank_tier, rank_division, league_points
FROM players WHERE puuid = ?
`

type GetPlayerRow struct {
	Puuid        string
	GameName     string
	TagLine      string
	Region       string
	RankTier     string
	RankDivision string
	LeaguePoints int64
}

func (q *Queries) GetPlayer(ctx context.Context, puuid string) (GetPlayerRow, error) {
	row := q.db.QueryRowContext(ctx, getPlayer, puuid)
	var i GetPlayerRow
	err := row.Scan(
		&i.Puuid,
		&i.GameName,
		&i.TagLine,
		&i.Region,
		&i.RankTier,
		&i.RankDivision,
		&i.LeaguePoints,
	)
	return i, err
}

const getPlayerControl = `-- name: GetPlayerControl :one
SELECT enabled, tags FROM player_controls
WHERE region = ? AND game_name = ? COLLATE NOCASE AND tag_line = ? COLLATE NOCASE
`

type GetPlayerControlParams struct {
	Region   string
	GameName string
	TagLine  string
}

type GetPlayerControlRow struct {
	Enabled int64
	Tags    string
}

func (q *Queries) GetPlayerControl(ctx context.Context, arg GetPlayerControlParams) (GetPlayerControlRow, error) {
	row := q.db.QueryRowContext(ctx, getPlayerControl, arg.Region, arg.GameName, arg.TagLine)
	var i GetPlayerControlRow
	err := row.Scan(&i.Enabled, &i.Tags)
	return i, err
}

const listActivePlayers = `-- name: ListActivePlayers :many
SELECT p.puuid, p.game_name, p.tag_line, p.region, p.rank_tier, p.rank_division, p.league_points
FROM players p LEFT JOIN player_controls c
  ON c.region = p.region AND c.game_name = p.game_name COLLATE NOCASE AND c.tag_line = p.tag_line COLLATE NOCASE
WHERE COALESCE(c.enabled, 1) = 1
ORDER BY p.game_name COLLATE NOCASE, p.tag_line COLLATE NOCASE
`

type ListActivePlayersRow struct {
	Puuid        string
	GameName     string
	TagLine      string
	Region       string
	RankTier     string
	RankDivision string
	LeaguePoints int64
}

func (q *Queries) ListActivePlayers(ctx context.Context) ([]ListActivePlayersRow, error) {
	rows, err := q.db.QueryContext(ctx, listActivePlayers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActivePlayersRow{}
	for rows.Next() {
		var i ListActivePlayersRow
		if err := rows.Scan(
			&i.Puuid,
			&i.GameName,
			&i.TagLine,
			&i.Region,
			&i.RankTier,
			&i.RankDivision,
			&i.LeaguePoints,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllPendingSeeds = `-- name: ListAllPendingSeeds :many
SELECT game_name, tag_line, region, source FROM player_seeds
WHERE resolved_puuid = ''
GROUP BY region, game_name, tag_line
ORDER BY region, game_name
`

type ListAllPendingSeedsRow struct {
	GameName string
	TagLine  string
	Region   string
	Source   string
}

func (q *Queries) ListAllPendingSeeds(ctx context.Context) ([]ListAllPendingSeedsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllPendingSeeds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllPendingSeedsRow{}
	for rows.Next() {
		var i ListAllPendingSeedsRow
		if err := rows.Scan(
			&i.GameName,
			&i.TagLine,
			&i.Region,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingSeeds = `-- name: ListPendingSeeds :many
SELECT game_name, tag_line, region, source FROM player_seeds
WHERE resolved_puuid = '' AND NOT EXISTS (
    SELECT 1 FROM player_controls c WHERE c.region = player_seeds.region
    AND c.game_name = player_seeds.game_name COLLATE NOCASE
    AND c.tag_line = player_seeds.tag_line COLLATE NOCASE AND c.enabled = 0)
GROUP BY region, game_name, tag_line
ORDER BY region, game_name
`

type ListPendingSeedsRow struct {
	GameName string
	TagLine  string
	Region   string
	Source   string
}

func (q *Queries) ListPendingSeeds(ctx context.Context) ([]ListPendingSeedsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPendingSeeds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingSeedsRow{}
	for rows.Next() {
		var i ListPendingSeedsRow
		if err := rows.Scan(
			&i.GameName,
			&i.TagLine,
			&i.Region,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayerChampions = `-- name: ListPlayerChampions :many
SELECT champion FROM player_champions
WHERE player_puuid = ? ORDER BY champion COLLATE NOCASE
`

func (q *Queries) ListPlayerChampions(ctx context.Context, playerPuuid string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listPlayerChampions, playerPuuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var champion string
		if err := rows.Scan(&champion); err != nil {
			return nil, err
		}
		items = append(items, champion)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayers = `-- name: ListPlayers :many
SELECT puuid, game_name, tag_line, region, rank_tier, rank_division, league_points
FROM players ORDER BY game_name COLLATE NOCASE, tag_line COLLATE NOCASE
`

type ListPlayersRow struct {
	Puuid        string
	GameName     string
	TagLine      string
	Region       string
	RankTier     string
	RankDivision string
	LeaguePoints int64
}

func (q *Queries) ListPlayers(ctx context.Context) ([]ListPlayersRow, error) {
	rows, err := q.db.QueryContext(ctx, listPlayers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlayersRow{}
	for rows.Next() {
		var i ListPlayersRow
		if err := rows.Scan(
			&i.Puuid,
			&i.GameName,
			&i.TagLine,
			&i.Region,
			&i.RankTier,
			&i.RankDivision,
			&i.LeaguePoints,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeedChampions = `-- name: ListSeedChampions :many
SELECT champion FROM player_seeds
WHERE region = ? AND game_name = ? AND tag_line = ?
`

type ListSeedChampionsParams struct {
	Region   string
	GameName string
	TagLine  string
}

func (q *Queries) ListSeedChampions(ctx context.Context, arg ListSeedChampionsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listSeedChampions, arg.Region, arg.GameName, arg.TagLine)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var champion string
		if err := rows.Scan(&champion); err != nil {
			return nil, err
		}
		items = append(items, champion)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveSeed = `-- name: ResolveSeed :exec
UPDATE player_seeds SET resolved_puuid = ?1
WHERE region = ?2 AND game_name = ?3 AND tag_line = ?4
`

type ResolveSeedParams struct {
	Puuid    string
	Region   string
	GameName string
	TagLine  string
}

func (q *Queries) ResolveSeed(ctx context.Context, arg ResolveSeedParams) error {
	_, err := q.db.ExecContext(ctx, resolveSeed,
		arg.Puuid,
		arg.Region,
		arg.GameName,
		arg.TagLine,
	)
	return err
}

const savePlayerControl = `-- name: SavePlayerControl :exec
INSERT INTO player_controls (region, game_name, tag_line, enabled, tags)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (region, game_name, tag_line) DO UPDATE SET enabled = excluded.enabled, tags = excluded.tags
`

type SavePlayerControlParams struct {
	Region   string
	GameName string
	TagLine  string
	Enabled  int64
	Tags     string
}

func (q *Queries) SavePlayerControl(ctx context.Context, arg SavePlayerControlParams) error {
	_, err := q.db.ExecContext(ctx, savePlayerControl,
		arg.Region,
		arg.GameName,
		arg.TagLine,
		arg.Enabled,
		arg.Tags,
	)
	return err
}

const updatePlayerRank = `-- name: UpdatePlayerRank :exec
UPDATE players
SET rank_tier = ?, rank_division = ?, league_points = ?, last_checked_at = ?
WHERE puuid = ?
`

type UpdatePlayerRankParams struct {
	RankTier      string
	RankDivision  string
	LeaguePoints  int64
	LastCheckedAt int64
	Puuid         string
}

func (q *Queries) UpdatePlayerRank(ctx context.Context, arg UpdatePlayerRankParams) error {
	_, err := q.db.ExecContext(ctx, updatePlayerRank,
		arg.RankTier,
		arg.RankDivision,
		arg.LeaguePoints,
		arg.LastCheckedAt,
		arg.Puuid,
	)
	return err
}

const upsertPlayer = `-- name: UpsertPlayer :exec
INSERT INTO players (puuid, game_name, tag_line, region, source)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (puuid) DO UPDATE SET
    game_name = excluded.game_name,
    tag_line = excluded.tag_line,
    region = excluded.region,
    source = excluded.source
`

type UpsertPlayerParams struct {
	Puuid    string
	GameName string
	TagLine  string
	Region   string
	Source   string
}

func (q *Queries) UpsertPlayer(ctx context.Context, arg UpsertPlayerParams) error {
	_, err := q.db.ExecContext(ctx, upsertPlayer,
		arg.Puuid,
		arg.GameName,
		arg.TagLine,
		arg.Region,
		arg.Source,
	)
	return err
}

const upsertSeed = `-- name: UpsertSeed :exec
INSERT INTO player_seeds (game_name, tag_line, region, champion, source, resolved_puuid)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT (region, game_name, tag_line, champion) DO UPDATE SET
    source = excluded.source,
    resolved_puuid = CASE WHEN player_seeds.resolved_puuid = ''
        THEN excluded.resolved_puuid ELSE player_seeds.resolved_puuid END
`

type UpsertSeedParams struct {
	GameName      string
	TagLine       string
	Region        string
	Champion      string
	Source        string
	ResolvedPuuid string
}

func (q *Queries) UpsertSeed(ctx context.Context, arg UpsertSeedParams) error {
	_, err := q.db.ExecContext(ctx, upsertSeed,
		arg.GameName,
		arg.TagLine,
		arg.Region,
		arg.Champion,
		arg.Source,
		arg.ResolvedPuuid,
	)
	return err
}
