// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: search.sql

package store

import (
	"context"
	"database/sql"
)

const searchGames = `-- name: SearchGames :many
WITH perspectives AS (
    SELECT g.match_id, g.player_puuid, g.opponent_puuid,
           g.player_rank_tier AS rank_tier, g.player_rank_division AS rank_division,
           g.matchup_status, 0 AS opponent_view
    FROM tracked_games g
    UNION ALL
    SELECT g.match_id, g.opponent_puuid, g.player_puuid,
           COALESCE(rp.rank_tier, ''), COALESCE(rp.rank_division, ''),
           g.matchup_status, 1
    FROM tracked_games g
    LEFT JOIN players rp ON rp.puuid = g.opponent_puuid
    WHERE g.opponent_puuid <> ''
      AND NOT EXISTS (SELECT 1 FROM tracked_games own
                      WHERE own.match_id = g.match_id AND own.player_puuid = g.opponent_puuid)
)
SELECT m.match_id, m.platform, m.game_version, m.game_creation,
       me.riot_id_game_name, me.riot_id_tagline,
       COALESCE(p.game_name, '') AS player_game_name, COALESCE(p.tag_line, '') AS player_tag_line,
       g.rank_tier, g.rank_division, g.matchup_status,
       me.champion, me.win, me.kills, me.deaths, me.assists, me.cs,
       me.summoner1_id, me.summoner2_id, me.keystone, me.secondary_rune1, me.secondary_rune2,
       opp.champion AS opponent_champion,
       opp.riot_id_game_name AS opponent_game_name, opp.riot_id_tagline AS opponent_tag_line,
       opp.kills AS opponent_kills, opp.deaths AS opponent_deaths, opp.assists AS opponent_assists
FROM perspectives g
JOIN matches m ON m.match_id = g.match_id
JOIN match_participants me ON me.match_id = g.match_id AND me.puuid = g.player_puuid
LEFT JOIN match_participants opp ON opp.match_id = g.match_id AND opp.puuid = g.opponent_puuid
LEFT JOIN players p ON p.puuid = g.player_puuid
WHERE (CAST(?1 AS TEXT) = '' OR m.platform = ?1 COLLATE NOCASE)
  AND (CAST(?2 AS TEXT) = '' OR me.champion = ?2 COLLATE NOCASE)
  AND (CAST(?3 AS TEXT) = '' OR opp.champion = ?3 COLLATE NOCASE)
  AND (CAST(?4 AS TEXT) = '' OR me.win = (?4 = 'win'))
  -- Exact KDA ratio comparison without floating point; unknown opponents never pass.
  AND (CAST(?5 AS TEXT) = '' OR (opp.kills IS NOT NULL AND (
        (?5 = 'ge' AND (me.kills + me.assists) * MAX(1, opp.deaths) >= (opp.kills + opp.assists) * MAX(1, me.deaths))
     OR (?5 = 'gt' AND (me.kills + me.assists) * MAX(1, opp.deaths) > (opp.kills + opp.assists) * MAX(1, me.deaths)))))
  AND (CAST(?6 AS INTEGER) = 0 OR CASE UPPER(g.rank_tier)
        WHEN 'EMERALD' THEN 1 WHEN 'DIAMOND' THEN 2 WHEN 'MASTER' THEN 3
        WHEN 'GRANDMASTER' THEN 4 WHEN 'CHALLENGER' THEN 5 ELSE 0 END >= ?6)
  AND m.game_creation >= ?7
  AND m.game_duration >= ?8
  AND (CAST(?9 AS INTEGER) = 0 OR (m.patch_major = ?9 AND m.patch_minor = ?10))
  AND (CAST(?11 AS TEXT) = '' OR me.riot_id_game_name = ?11 COLLATE NOCASE
       OR p.game_name = ?11 COLLATE NOCASE OR g.player_puuid = ?11)
ORDER BY m.game_creation DESC, m.match_id DESC, g.opponent_view
`

type SearchGamesParams struct {
	Region       string
	Champion     string
	Opponent     string
	Result       string
	Kda          string
	MinRank      int64
	CreatedSince int64
	MinDuration  int64
	PatchMajor   int64
	PatchMinor   int64
	Player       string
}

type SearchGamesRow struct {
	MatchID          string
	Platform         string
	GameVersion      string
	GameCreation     int64
	RiotIDGameName   string
	RiotIDTagline    string
	PlayerGameName   string
	PlayerTagLine    string
	RankTier         string
	RankDivision     string
	MatchupStatus    string
	Champion         string
	Win              bool
	Kills            int64
	Deaths           int64
	Assists          int64
	Cs               int64
	Summoner1ID      sql.NullInt64
	Summoner2ID      sql.NullInt64
	Keystone         sql.NullInt64
	SecondaryRune1   sql.NullInt64
	SecondaryRune2   sql.NullInt64
	OpponentChampion sql.NullString
	OpponentGameName sql.NullString
	OpponentTagLine  sql.NullString
	OpponentKills    sql.NullInt64
	OpponentDeaths   sql.NullInt64
	OpponentAssists  sql.NullInt64
}

// Every tracked game is searchable from both sides: the tracked player's and,
// unless the opponent is tracked too, the lane opponent's (listed second). The opponent's rank
// is known only when the opponent is a tracked player. Empty/zero parameters
// disable their filter. Results are newest first.
func (q *Queries) SearchGames(ctx context.Context, arg SearchGamesParams) ([]SearchGamesRow, error) {
	rows, err := q.db.QueryContext(ctx, searchGames,
		arg.Region,
		arg.Champion,
		arg.Opponent,
		arg.Result,
		arg.Kda,
		arg.MinRank,
		arg.CreatedSince,
		arg.MinDuration,
		arg.PatchMajor,
		arg.PatchMinor,
		arg.Player,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchGamesRow{}
	for rows.Next() {
		var i SearchGamesRow
		if err := rows.Scan(
			&i.MatchID,
			&i.Platform,
			&i.GameVersion,
			&i.GameCreation,
			&i.RiotIDGameName,
			&i.RiotIDTagline,
			&i.PlayerGameName,
			&i.PlayerTagLine,
			&i.RankTier,
			&i.RankDivision,
			&i.MatchupStatus,
			&i.Champion,
			&i.Win,
			&i.Kills,
			&i.Deaths,
			&i.Assists,
			&i.Cs,
			&i.Summoner1ID,
			&i.Summoner2ID,
			&i.Keystone,
			&i.SecondaryRune1,
			&i.SecondaryRune2,
			&i.OpponentChampion,
			&i.OpponentGameName,
			&i.OpponentTagLine,
			&i.OpponentKills,
			&i.OpponentDeaths,
			&i.OpponentAssists,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
